-- MySQL Script generated by MySQL Workbench
-- Fri 22 Jul 2022 08:16:40 PM WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- ----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nama_user` VARCHAR(60) NULL,
  `alamat` VARCHAR(100) NULL,
  `noHp` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `level` ENUM('pemilik', 'admin', 'dokter', 'pasien') NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_user_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_login_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dokter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dokter` (
  `iddokter` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`iddokter`),
  INDEX `fk_dokter_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_dokter_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jadwal_praktik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jadwal_praktik` (
  `idjadwal_praktik` INT NOT NULL AUTO_INCREMENT,
  `hari` VARCHAR(45) NULL,
  `jam` VARCHAR(45) NULL,
  `dokter_iddokter` INT NOT NULL,
  PRIMARY KEY (`idjadwal_praktik`),
  INDEX `fk_jadwal_praktik_dokter1_idx` (`dokter_iddokter` ASC),
  CONSTRAINT `fk_jadwal_praktik_dokter1`
    FOREIGN KEY (`dokter_iddokter`)
    REFERENCES `dokter` (`iddokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transaksi` (
  `idtransaksi` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`idtransaksi`),
  INDEX `fk_transaksi_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_transaksi_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`barang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barang` (
  `idbarang` INT NOT NULL AUTO_INCREMENT,
  `nama_barang` VARCHAR(45) NULL,
  `harga_barang` INT NULL,
  `stok_barang` INT NULL,
  PRIMARY KEY (`idbarang`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaksi_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transaksi_detail` (
  `idtransaksi_detail` INT NOT NULL AUTO_INCREMENT,
  `transaksi_idtransaksi` INT NOT NULL,
  `barang_idbarang` INT NOT NULL,
  PRIMARY KEY (`idtransaksi_detail`),
  INDEX `fk_transaksi_detail_transaksi1_idx` (`transaksi_idtransaksi` ASC) ,
  INDEX `fk_transaksi_detail_barang1_idx` (`barang_idbarang` ASC) ,
  CONSTRAINT `fk_transaksi_detail_transaksi1`
    FOREIGN KEY (`transaksi_idtransaksi`)
    REFERENCES `transaksi` (`idtransaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaksi_detail_barang1`
    FOREIGN KEY (`barang_idbarang`)
    REFERENCES `barang` (`idbarang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pasien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pasien` (
  `idpasien` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idpasien`),
  INDEX `fk_pasien_user1_idx` (`user_iduser` ASC) ,
  CONSTRAINT `fk_pasien_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`praktik_dijadwalkan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `praktik_dijadwalkan` (
  `idpraktik_dijadwalkan` INT NOT NULL AUTO_INCREMENT,
  `tanggal` DATE NULL,
  `keterangan` VARCHAR(45) NULL,
  `jadwal_praktik_idjadwal_praktik` INT NOT NULL,
  `pasien_idpasien` INT NOT NULL,
  `dokter_iddokter` INT NOT NULL,
  `status` ENUM('1', '0') NULL,
  PRIMARY KEY (`idpraktik_dijadwalkan`),
  INDEX `fk_praktik_dijadwalkan_jadwal_praktik1_idx` (`jadwal_praktik_idjadwal_praktik` ASC) ,
  INDEX `fk_praktik_dijadwalkan_pasien1_idx` (`pasien_idpasien` ASC) ,
  INDEX `fk_praktik_dijadwalkan_dokter1_idx` (`dokter_iddokter` ASC) ,
  CONSTRAINT `fk_praktik_dijadwalkan_jadwal_praktik1`
    FOREIGN KEY (`jadwal_praktik_idjadwal_praktik`)
    REFERENCES `jadwal_praktik` (`idjadwal_praktik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_praktik_dijadwalkan_pasien1`
    FOREIGN KEY (`pasien_idpasien`)
    REFERENCES `pasien` (`idpasien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_praktik_dijadwalkan_dokter1`
    FOREIGN KEY (`dokter_iddokter`)
    REFERENCES `dokter` (`iddokter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
